services:
  - type: web
    name: heat-health-monitoring
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    region: oregon
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: SENSOR_SECRET
        sync: false
      - key: HEALTH_WORKER_CODE
        sync: false
      - key: DEFAULT_CITY
        value: Clarin,Bohol,PH
      - key: RUN_SCHEDULER
        value: "true"
