"""Add purok field to Temperature, HeatIndex, and Resident models

Revision ID: bb1de519f18e
Revises: 
Create Date: 2026-04-27 21:34:44.690863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1de519f18e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heat_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purok', sa.String(length=50), nullable=True))

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purok', sa.String(length=50), nullable=True))

    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purok', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.drop_column('purok')

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_column('purok')

    with op.batch_alter_table('heat_index', schema=None) as batch_op:
        batch_op.drop_column('purok')

    # ### end Alembic commands ###
